finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # '' is root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    # new route for details!
    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
    # new route to show form and create finch
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
    # routes for update/delete
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_sighting/', views.add_sighting, name='add_sighting'),
    path('finches/<int:finch_id>/assoc_predator/<int:predator_id>/', views.assoc_predator, name='assoc_predator'),
    path('predators/', views.PredatorList.as_view(), name='predators_index'),
    path('predators/<int:pk>/', views.PredatorDetail.as_view(), name='predators_detail'),
    path('predators/create/', views.PredatorCreate.as_view(), name='predators_create'),
    path('predators/<int:pk>/update/', views.PredatorUpdate.as_view(), name='predators_update'),
    path('predators/<int:pk>/delete/', views.PredatorDelete.as_view(), name='predators_delete'),
]   

main_app/models.py
from smtplib import SMTPRecipientsRefused
from django.db import models
from django.urls import reverse

# Create your models here.

class Predator(models.Model):
    commonName = models.CharField(max_length=50)
    description = models.CharField(max_length=250)

    def __str__(self):
        return self.commonName
    
    def get_absolute_url(self):
        return reverse('predators_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    commonName = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    iocSequence = models.IntegerField()
    # Adding M:M relationship
    predators = models.ManyToManyField(Predator)

    def __str__(self):
        return f'{self.commonName} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})

class Sighting(models.Model):
    date = models.DateField('sighting date')
    location = models.CharField(max_length=50)

    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.location} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from calendar import c
from django.forms import ModelForm
from .models import Sighting

class SightingForm(ModelForm):
    class Meta:
        model = Sighting
        fields = ['date', 'location']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Finch, Predator
from .forms import SightingForm


class FinchCreate(CreateView):
    model = Finch
    fields = ['commonName', 'species', 'description', 'iocSequence']

class FinchUpdate(UpdateView):
    model = Finch
    fields = ['species','description', 'iocSequence']

class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches/'

# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', { 'finches': finches })

def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    id_list = finch.predators.all().values_list('id')
    predators_finch_doesnt_have = Predator.objects.exclude(id__in=id_list)
    sighting_form = SightingForm()
    return render(request, 'finches/detail.html', {
        'finch': finch, 'sighting_form': sighting_form,
         'predators': predators_finch_doesnt_have
    })

def add_sighting(request, finch_id):
    form = SightingForm(request.POST)
    #validate the form
    if form.is_valid():
        # dont save the form to database until
        # has finch_id assigned
        new_sighting = form.save(commit=False)
        new_sighting.finch_id = finch_id
        new_sighting.save()
    return redirect('detail', finch_id=finch_id)

class PredatorList(ListView):
  model = Predator

class PredatorDetail(DetailView):
  model = Predator

class PredatorCreate(CreateView):
  model = Predator
  fields = '__all__'

class PredatorUpdate(UpdateView):
  model = Predator
  fields = ['commonName', 'description']

class PredatorDelete(DeleteView):
  model = Predator
  success_url = '/predators/'

def assoc_predator(request, finch_id, predator_id):
    Finch.objects.get(id=finch_id).predators.add(predator_id)
    return redirect('detail', finch_id=finch_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About the Finch Collector</h1>
    <hr />
    <p></p>
    <footer>All Rights Reserved, &copy; 2022 Finch Collector</footer>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Finch Collector</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'predators_create' %}">Add a Predator</a></li>
          <li><a href="{% url 'predators_index' %}">View All Predators</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View the Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.commonName }}</span>
        <p>Species: {{ finch.species }}</p>
        <p>Description: {{ finch.description|linebreaks }}</p>
        <p>IOC Sequence: {{ finch.iocSequence }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Edit</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_sighting' finch.id %}" method="POST">
      {% csrf_token %}
      {{ sighting_form.as_p }}
      <input type="submit" class="btn" value="Add Sighting">
    </form>
    <br>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Location</th></tr>
      </thead>
      <tbody>
        {% for sighting in finch.sighting_set.all %}
        <tr>
          <td>{{sighting.date}}</td>
          <td>{{sighting.location}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col s6">
      <h3>{{ finch.commonName }}'s Predators</h3>
      {% if finch.predators.count %}
        {% for predator in finch.predators.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">{{ predator.commonName }}</span>
              <p>Description: {{ predator.description }}</p>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Predators :)</h5>
      {% endif %}
    </div>
  </div>
</div>

<div class="col s6">
  <h3>Predator List</h3>
  {% if predators.count %}
    {% for predator in predators.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            <a href="{% url 'predators_detail' predator.id %}">{{ predator.commonName }}</a>
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_predator' finch.id predator.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <h5>{{finch.commonName}} is prey to all listed predators :(</h5>
  {% endif %}
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
  format: 'yyyy-mm-dd',
  defaultDate: new Date(),
  setDefaultDate: true,
  autoClose: true
  });  
</script>
{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
  <div class="card">
    <a href="{% url 'detail' finch.id %}"
      <div class="card-content">
        <span class="card-title">{{ finch.commonName }}</span>
        <p>Species: {{ finch.species }}</p>
        <p>Description: {{ finch.description }}</p>
        <p>IOC Sequence: {{ finch.iocSequence }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.commonName }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.commonName}}</span></h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/predator_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Predator</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'predators_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/predator_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Predator Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ predator.commonName }}</span>
        <p>Description: {{ predator.description|linebreaks }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'predators_update' predator.id %}">Edit</a>
        <a href="{% url 'predators_delete' predator.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/predator_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Predator</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/predator_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Predator List</h1>

{% for predator in predator_list %}
  <a href="{% url 'predators_detail' predator.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ predator.commonName }}</span>
            <p>Description: {{ predator.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}